version: '3'

services:
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_node
    restart: always
    tty: true
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
  
  server:
    build:
      context: node
    container_name: server
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: node index.js
    networks:
      - nodenet
    tty: true
    ports:
      - 3030:3030
    depends_on:
      - db
    restart: unless-stopped
  
  nginx:
    build:
      context: nginx
    container_name: nginx_node
    networks:
      - nodenet
    ports:
      - 8080:80
    depends_on:
      - server
    restart: unless-stopped


networks:
  nodenet:
    driver: bridge